In [1]:
import pandas as pd

df = pd.read_csv('train.csv')

/Users/federicoungarelli/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (30) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [2]:
import pandas as pd

test_df = pd.read_csv('test.csv')

In [3]:
df2 = df.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                'neighbourhood_group_cleansed', 'instant_bookable', 'number_of_reviews','reviews_per_month', 'host_response_rate',
                 'host_is_superhost', 'host_listings_count', 'host_has_profile_pic', 'property_type', 'bed_type', 'maximum_nights', 'cancellation_policy',
                 'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication','require_guest_phone_verification',
                  'price']]
df2

,guests_included,extra_people,bedrooms,bathrooms,minimum_nights,review_scores_rating,neighbourhood_group_cleansed,instant_bookable,number_of_reviews,reviews_per_month,...,bed_type,maximum_nights,cancellation_policy,review_scores_cleanliness,calculated_host_listings_count,review_scores_accuracy,review_scores_checkin,review_scores_communication,require_guest_phone_verification,price
0,2,$30.00,1.0,1.0,7,100.0,Brooklyn,t,6,0.59,...,Real Bed,12,flexible,10.0,1,10.0,10.0,10.0,f,145.0
1,3,$19.00,3.0,1.0,3,91.0,Manhattan,t,137,2.47,...,Real Bed,30,moderate,9.0,3,9.0,9.0,9.0,f,175.0
2,1,$0.00,0.0,1.0,2,100.0,Manhattan,f,3,0.89,...,Real Bed,1125,moderate,9.0,1,10.0,9.0,10.0,f,180.0
3,1,$0.00,1.0,1.0,3,NaN,Brooklyn,f,0,NaN,...,Real Bed,1125,flexible,NaN,1,NaN,NaN,NaN,f,42.0
4,1,$14.00,1.0,1.0,1,97.0,Brooklyn,f,144,3.14,...,Real Bed,90,flexible,10.0,1,10.0,10.0,10.0,f,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33533,1,$25.00,1.0,1.0,3,87.0,Manhattan,f,19,0.44,...,Real Bed,1125,strict_14_with_grace_period,8.0,1,9.0,9.0,9.0,f,110.0
33534,1,$0.00,4.0,3.0,3,95.0,Manhattan,f,86,2.28,...,Real Bed,365,strict_14_with_grace_period,9.0,1,10.0,10.0,10.0,f,1195.0
33535,1,$0.00,1.0,NaN,180,NaN,Queens,f,0,NaN,...,Real Bed,365,flexible,NaN,1,NaN,NaN,NaN,f,50.0
33536,1,$0.00,1.0,1.0,7,100.0,Manhattan,f,1,0.10,...,Real Bed,1125,moderate,10.0,3,10.0,10.0,10.0,f,60.0
33537,4,$25.00,3.0,2.0,5,95.0,Manhattan,t,56,2.76,...,Real Bed,120,strict_14_with_grace_period,9.0,1,9.0,10.0,10.0,f,325.0

In [4]:
df2['extra_people'] = df2['extra_people'].str.replace('$', '')
df2['extra_people'] = df2['extra_people'].str.replace('.00', '')
df2['extra_people'] = df2['extra_people'].replace('', 0)
df2['host_response_rate'] = df2['host_response_rate'].str.replace('%', '')

In [5]:
df2.fillna(-1, inplace=True)

In [6]:
df2['extra_people'] = df2['extra_people'].astype(int)
df2['guests_included'] = df2['guests_included'].astype(int)
df2['bedrooms'] = df2['bedrooms'].astype(int)
df2['bathrooms'] = df2['bathrooms'].astype(int)
df2['minimum_nights'] = df2['minimum_nights'].astype(int)
df2['maximum_nights'] = df2['maximum_nights'].astype(int)
df2['number_of_reviews'] = df2['number_of_reviews'].astype(int)
df2['reviews_per_month'] = df2['reviews_per_month'].astype(int)
df2['host_response_rate'] = df2['host_response_rate'].astype(int)
df2['calculated_host_listings_count'] = df2['calculated_host_listings_count'].astype(int)
df2['review_scores_accuracy'] = df2['review_scores_accuracy'].astype(float)
df2['review_scores_checkin'] = df2['review_scores_checkin'].astype(float)
df2['review_scores_communication'] = df2['review_scores_communication'].astype(float)

In [7]:
df2

,guests_included,extra_people,bedrooms,bathrooms,minimum_nights,review_scores_rating,neighbourhood_group_cleansed,instant_bookable,number_of_reviews,reviews_per_month,...,bed_type,maximum_nights,cancellation_policy,review_scores_cleanliness,calculated_host_listings_count,review_scores_accuracy,review_scores_checkin,review_scores_communication,require_guest_phone_verification,price
0,2,30,1,1,7,100.0,Brooklyn,t,6,0,...,Real Bed,12,flexible,10.0,1,10.0,10.0,10.0,f,145.0
1,3,19,3,1,3,91.0,Manhattan,t,137,2,...,Real Bed,30,moderate,9.0,3,9.0,9.0,9.0,f,175.0
2,1,0,0,1,2,100.0,Manhattan,f,3,0,...,Real Bed,1125,moderate,9.0,1,10.0,9.0,10.0,f,180.0
3,1,0,1,1,3,-1.0,Brooklyn,f,0,-1,...,Real Bed,1125,flexible,-1.0,1,-1.0,-1.0,-1.0,f,42.0
4,1,14,1,1,1,97.0,Brooklyn,f,144,3,...,Real Bed,90,flexible,10.0,1,10.0,10.0,10.0,f,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33533,1,25,1,1,3,87.0,Manhattan,f,19,0,...,Real Bed,1125,strict_14_with_grace_period,8.0,1,9.0,9.0,9.0,f,110.0
33534,1,0,4,3,3,95.0,Manhattan,f,86,2,...,Real Bed,365,strict_14_with_grace_period,9.0,1,10.0,10.0,10.0,f,1195.0
33535,1,0,1,-1,180,-1.0,Queens,f,0,-1,...,Real Bed,365,flexible,-1.0,1,-1.0,-1.0,-1.0,f,50.0
33536,1,0,1,1,7,100.0,Manhattan,f,1,0,...,Real Bed,1125,moderate,10.0,3,10.0,10.0,10.0,f,60.0
33537,4,25,3,2,5,95.0,Manhattan,t,56,2,...,Real Bed,120,strict_14_with_grace_period,9.0,1,9.0,10.0,10.0,f,325.0

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33538 entries, 0 to 33537
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   guests_included                   33538 non-null  int64
 1   extra_people                      33538 non-null  int64
 2   bedrooms                          33538 non-null  int64
 3   bathrooms                         33538 non-null  int64
 4   minimum_nights                    33538 non-null  int64
 5   review_scores_rating              33538 non-null  float64
 6   neighbourhood_group_cleansed      33538 non-null  object
 7   instant_bookable                  33538 non-null  object
 8   number_of_reviews                 33538 non-null  int64
 9   reviews_per_month                 33538 non-null  int64
 10  host_response_rate                33538 non-null  int64
 11  host_is_superhost                 33538 non-null  object
 12  host_listings_count               33538 non-null  float64
 13  host_has_profile_pic              33538 non-null  object
 14  property_type                     33538 non-null  object
 15  bed_type                          33538 non-null  object
 16  maximum_nights                    33538 non-null  int64
 17  cancellation_policy               33538 non-null  object
 18  review_scores_cleanliness         33538 non-null  float64
 19  calculated_host_listings_count    33538 non-null  int64
 20  review_scores_accuracy            33538 non-null  float64
 21  review_scores_checkin             33538 non-null  float64
 22  review_scores_communication       33538 non-null  float64
 23  require_guest_phone_verification  33538 non-null  object
 24  price                             33538 non-null  float64
dtypes: float64(7), int64(10), object(8)
memory usage: 6.4+ MB

# Replace Nans

In [9]:
import numpy as np
df2.replace(-1, np.nan, inplace = True)

In [10]:
#df2.fillna(df2.mean(), inplace = True)
#df2 = df2.dropna()

In [11]:
train_X = df2.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                'neighbourhood_group_cleansed', 'instant_bookable', 'number_of_reviews','reviews_per_month','host_response_rate',
                 'host_is_superhost', 'host_listings_count', 'host_has_profile_pic', 'property_type', 'bed_type', 'maximum_nights', 'cancellation_policy',
                     'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication','require_guest_phone_verification']]
train_y = df2.loc[:, ['price']]

In [12]:
train_X.isna().sum()

guests_included                         0
extra_people                            0
bedrooms                               33
bathrooms                              60
minimum_nights                          0
review_scores_rating                 7664
neighbourhood_group_cleansed            0
instant_bookable                        0
number_of_reviews                       0
reviews_per_month                    6947
host_response_rate                  16193
host_is_superhost                       5
host_listings_count                     5
host_has_profile_pic                    5
property_type                           0
bed_type                                0
maximum_nights                          0
cancellation_policy                     0
review_scores_cleanliness            7679
calculated_host_listings_count          0
review_scores_accuracy               7694
review_scores_checkin                7709
review_scores_communication          7689
require_guest_phone_verification        0
dtype: int64

In [13]:
from sklearn.impute import SimpleImputer

In [14]:
imp = SimpleImputer(strategy='most_frequent')
train_X.loc[:, ['neighbourhood_group_cleansed', 'instant_bookable', 
                 'host_is_superhost', 'host_has_profile_pic', 'property_type', 'bed_type', 'cancellation_policy'
                     ,'require_guest_phone_verification']] = imp.fit_transform(train_X.loc[:, ['neighbourhood_group_cleansed', 'instant_bookable', 
                    'host_is_superhost', 'host_has_profile_pic', 'property_type', 
                    'bed_type', 'cancellation_policy' ,'require_guest_phone_verification']])

In [15]:
imp1 = SimpleImputer(strategy='median')
train_X.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                 'number_of_reviews','reviews_per_month','host_response_rate',
                'host_listings_count', 'maximum_nights', 'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication']] = imp1.fit_transform(train_X.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                 'number_of_reviews','reviews_per_month','host_response_rate',
                'host_listings_count', 'maximum_nights', 'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication']])

In [16]:
train_X.isna().sum()

guests_included                     0
extra_people                        0
bedrooms                            0
bathrooms                           0
minimum_nights                      0
review_scores_rating                0
neighbourhood_group_cleansed        0
instant_bookable                    0
number_of_reviews                   0
reviews_per_month                   0
host_response_rate                  0
host_is_superhost                   0
host_listings_count                 0
host_has_profile_pic                0
property_type                       0
bed_type                            0
maximum_nights                      0
cancellation_policy                 0
review_scores_cleanliness           0
calculated_host_listings_count      0
review_scores_accuracy              0
review_scores_checkin               0
review_scores_communication         0
require_guest_phone_verification    0
dtype: int64

In [17]:
train_X = pd.get_dummies(train_X, drop_first = True)

In [18]:
train_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33538 entries, 0 to 33537
Data columns (total 62 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   guests_included                                  33538 non-null  float64
 1   extra_people                                     33538 non-null  float64
 2   bedrooms                                         33538 non-null  float64
 3   bathrooms                                        33538 non-null  float64
 4   minimum_nights                                   33538 non-null  float64
 5   review_scores_rating                             33538 non-null  float64
 6   number_of_reviews                                33538 non-null  float64
 7   reviews_per_month                                33538 non-null  float64
 8   host_response_rate                               33538 non-null  float64
 9   host_listings_count                              33538 non-null  float64
 10  maximum_nights                                   33538 non-null  float64
 11  review_scores_cleanliness                        33538 non-null  float64
 12  calculated_host_listings_count                   33538 non-null  float64
 13  review_scores_accuracy                           33538 non-null  float64
 14  review_scores_checkin                            33538 non-null  float64
 15  review_scores_communication                      33538 non-null  float64
 16  neighbourhood_group_cleansed_Brooklyn            33538 non-null  uint8
 17  neighbourhood_group_cleansed_Manhattan           33538 non-null  uint8
 18  neighbourhood_group_cleansed_Queens              33538 non-null  uint8
 19  neighbourhood_group_cleansed_Staten Island       33538 non-null  uint8
 20  instant_bookable_t                               33538 non-null  uint8
 21  host_is_superhost_t                              33538 non-null  uint8
 22  host_has_profile_pic_t                           33538 non-null  uint8
 23  property_type_Apartment                          33538 non-null  uint8
 24  property_type_Bed and breakfast                  33538 non-null  uint8
 25  property_type_Boat                               33538 non-null  uint8
 26  property_type_Boutique hotel                     33538 non-null  uint8
 27  property_type_Bungalow                           33538 non-null  uint8
 28  property_type_Cabin                              33538 non-null  uint8
 29  property_type_Camper/RV                          33538 non-null  uint8
 30  property_type_Casa particular (Cuba)             33538 non-null  uint8
 31  property_type_Chalet                             33538 non-null  uint8
 32  property_type_Condominium                        33538 non-null  uint8
 33  property_type_Cottage                            33538 non-null  uint8
 34  property_type_Guest suite                        33538 non-null  uint8
 35  property_type_Guesthouse                         33538 non-null  uint8
 36  property_type_Hostel                             33538 non-null  uint8
 37  property_type_Hotel                              33538 non-null  uint8
 38  property_type_House                              33538 non-null  uint8
 39  property_type_Houseboat                          33538 non-null  uint8
 40  property_type_Island                             33538 non-null  uint8
 41  property_type_Loft                               33538 non-null  uint8
 42  property_type_Other                              33538 non-null  uint8
 43  property_type_Resort                             33538 non-null  uint8
 44  property_type_Serviced apartment                 33538 non-null  uint8
 45  property_type_Tent                               33538 non-null  uint8
 46  property_type_Timeshare                          33538 non-null  uint8
 47  property_type_Tiny house                         33538 non-null  uint8
 48  property_type_Townhouse                          33538 non-null  uint8
 49  property_type_Train                              33538 non-null  uint8
 50  property_type_Villa                              33538 non-null  uint8
 51  bed_type_Couch                                   33538 non-null  uint8
 52  bed_type_Futon                                   33538 non-null  uint8
 53  bed_type_Pull-out Sofa                           33538 non-null  uint8
 54  bed_type_Real Bed                                33538 non-null  uint8
 55  cancellation_policy_long_term                    33538 non-null  uint8
 56  cancellation_policy_moderate                     33538 non-null  uint8
 57  cancellation_policy_strict                       33538 non-null  uint8
 58  cancellation_policy_strict_14_with_grace_period  33538 non-null  uint8
 59  cancellation_policy_super_strict_30              33538 non-null  uint8
 60  cancellation_policy_super_strict_60              33538 non-null  uint8
 61  require_guest_phone_verification_t               33538 non-null  uint8
dtypes: float64(16), uint8(46)
memory usage: 5.6 MB

# Test Set

In [19]:
test_df = test_df.loc[:, ['id','guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                'neighbourhood_group_cleansed', 'instant_bookable', 'number_of_reviews','reviews_per_month', 'host_response_rate',
                 'host_is_superhost', 'host_listings_count', 'host_has_profile_pic', 'property_type', 'bed_type', 'maximum_nights', 'cancellation_policy',
                         'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication','require_guest_phone_verification',]]

In [20]:
test_df['extra_people'] = test_df['extra_people'].str.replace('$', '')
test_df['extra_people'] = test_df['extra_people'].str.replace('.00', '')
test_df['extra_people'] = test_df['extra_people'].replace('', 0)
test_df['host_response_rate'] = test_df['host_response_rate'].str.replace('%', '')

In [21]:
test_df.fillna(-1, inplace=True)

In [22]:
test_df['extra_people'] = test_df['extra_people'].astype(int)
test_df['guests_included'] = test_df['guests_included'].astype(int)
test_df['bedrooms'] = test_df['bedrooms'].astype(int)
test_df['bathrooms'] = test_df['bathrooms'].astype(int)
test_df['minimum_nights'] = test_df['minimum_nights'].astype(int)
test_df['maximum_nights'] = test_df['maximum_nights'].astype(int)
test_df['number_of_reviews'] = test_df['number_of_reviews'].astype(int)
test_df['reviews_per_month'] = test_df['reviews_per_month'].astype(int)
test_df['host_response_rate'] = test_df['host_response_rate'].astype(int)
test_df['review_scores_rating'] = test_df['review_scores_rating'].astype(float)

In [23]:
test_df.replace(-1, np.nan, inplace = True)

In [24]:
test_ids = test_df.loc[:, 'id']
test_X = test_df.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                'neighbourhood_group_cleansed', 'instant_bookable', 'number_of_reviews','reviews_per_month','host_response_rate',
                 'host_is_superhost', 'host_listings_count', 'host_has_profile_pic', 'property_type', 'bed_type', 'maximum_nights', 'cancellation_policy'
                        ,'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication','require_guest_phone_verification']]

In [25]:
imp = SimpleImputer(strategy='most_frequent')
test_X.loc[:, ['neighbourhood_group_cleansed', 'instant_bookable', 
                 'host_is_superhost', 'host_has_profile_pic', 'property_type', 'bed_type', 'cancellation_policy'
                     ,'require_guest_phone_verification']] = imp.fit_transform(test_X.loc[:, ['neighbourhood_group_cleansed', 'instant_bookable', 
                 'host_is_superhost', 'host_has_profile_pic', 'property_type', 'bed_type', 'cancellation_policy'
                     ,'require_guest_phone_verification']])

In [26]:
imp1 = SimpleImputer(strategy='median')
test_X.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                 'number_of_reviews','reviews_per_month','host_response_rate',
                'host_listings_count', 'maximum_nights', 'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication']] = imp1.fit_transform(test_X.loc[:, ['guests_included',  'extra_people', 'bedrooms', 'bathrooms', 'minimum_nights', 'review_scores_rating', 
                 'number_of_reviews','reviews_per_month','host_response_rate',
                'host_listings_count', 'maximum_nights', 'review_scores_cleanliness','calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_checkin',
                 'review_scores_communication']])

In [27]:
test_X = pd.get_dummies(test_X, drop_first = True)

In [28]:
test_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17337 entries, 0 to 17336
Data columns (total 60 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   guests_included                                  17337 non-null  float64
 1   extra_people                                     17337 non-null  float64
 2   bedrooms                                         17337 non-null  float64
 3   bathrooms                                        17337 non-null  float64
 4   minimum_nights                                   17337 non-null  float64
 5   review_scores_rating                             17337 non-null  float64
 6   number_of_reviews                                17337 non-null  float64
 7   reviews_per_month                                17337 non-null  float64
 8   host_response_rate                               17337 non-null  float64
 9   host_listings_count                              17337 non-null  float64
 10  maximum_nights                                   17337 non-null  float64
 11  review_scores_cleanliness                        17337 non-null  float64
 12  calculated_host_listings_count                   17337 non-null  float64
 13  review_scores_accuracy                           17337 non-null  float64
 14  review_scores_checkin                            17337 non-null  float64
 15  review_scores_communication                      17337 non-null  float64
 16  neighbourhood_group_cleansed_Brooklyn            17337 non-null  uint8
 17  neighbourhood_group_cleansed_Manhattan           17337 non-null  uint8
 18  neighbourhood_group_cleansed_Queens              17337 non-null  uint8
 19  neighbourhood_group_cleansed_Staten Island       17337 non-null  uint8
 20  instant_bookable_t                               17337 non-null  uint8
 21  host_is_superhost_t                              17337 non-null  uint8
 22  host_has_profile_pic_t                           17337 non-null  uint8
 23  property_type_Apartment                          17337 non-null  uint8
 24  property_type_Bed and breakfast                  17337 non-null  uint8
 25  property_type_Boat                               17337 non-null  uint8
 26  property_type_Boutique hotel                     17337 non-null  uint8
 27  property_type_Bungalow                           17337 non-null  uint8
 28  property_type_Cabin                              17337 non-null  uint8
 29  property_type_Camper/RV                          17337 non-null  uint8
 30  property_type_Casa particular (Cuba)             17337 non-null  uint8
 31  property_type_Castle                             17337 non-null  uint8
 32  property_type_Cave                               17337 non-null  uint8
 33  property_type_Condominium                        17337 non-null  uint8
 34  property_type_Cottage                            17337 non-null  uint8
 35  property_type_Earth house                        17337 non-null  uint8
 36  property_type_Guest suite                        17337 non-null  uint8
 37  property_type_Guesthouse                         17337 non-null  uint8
 38  property_type_Hostel                             17337 non-null  uint8
 39  property_type_Hotel                              17337 non-null  uint8
 40  property_type_House                              17337 non-null  uint8
 41  property_type_Loft                               17337 non-null  uint8
 42  property_type_Nature lodge                       17337 non-null  uint8
 43  property_type_Other                              17337 non-null  uint8
 44  property_type_Resort                             17337 non-null  uint8
 45  property_type_Serviced apartment                 17337 non-null  uint8
 46  property_type_Tent                               17337 non-null  uint8
 47  property_type_Tiny house                         17337 non-null  uint8
 48  property_type_Townhouse                          17337 non-null  uint8
 49  property_type_Villa                              17337 non-null  uint8
 50  bed_type_Couch                                   17337 non-null  uint8
 51  bed_type_Futon                                   17337 non-null  uint8
 52  bed_type_Pull-out Sofa                           17337 non-null  uint8
 53  bed_type_Real Bed                                17337 non-null  uint8
 54  cancellation_policy_moderate                     17337 non-null  uint8
 55  cancellation_policy_strict                       17337 non-null  uint8
 56  cancellation_policy_strict_14_with_grace_period  17337 non-null  uint8
 57  cancellation_policy_super_strict_30              17337 non-null  uint8
 58  cancellation_policy_super_strict_60              17337 non-null  uint8
 59  require_guest_phone_verification_t               17337 non-null  uint8
dtypes: float64(16), uint8(44)
memory usage: 2.8 MB

In [29]:
train_X.drop('cancellation_policy_long_term', axis=1, inplace=True)
#train_X.drop('host_is_superhost_f', axis=1, inplace=True)
train_X.drop('property_type_Chalet', axis=1, inplace=True)
train_X.drop('property_type_Island', axis=1, inplace=True)
train_X.drop('property_type_Houseboat', axis=1, inplace=True)
train_X.drop('property_type_Train', axis=1, inplace=True)
train_X.drop('property_type_Timeshare', axis=1, inplace=True)
#train_X.drop('host_has_profile_pic_f', axis=1, inplace=True)

In [30]:
test_X = test_X.drop(columns=['property_type_Nature lodge', 'property_type_Castle', 'property_type_Cave', 'property_type_Earth house'], axis = 1)

In [31]:
from sklearn.model_selection import train_test_split
train_X_1, val_X, train_y_1, val_y = train_test_split(train_X, train_y, test_size=0.20, random_state=16)

In [32]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, truncnorm
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(40, 1000, num = 20)]
# Number of features to consider at every split
max_features = ['auto','sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [40, 90, 141, 191, 242, 292, 343, 393, 444, 494, 545, 595, 646, 696, 747, 797, 848, 898, 949, 1000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}

In [33]:
from sklearn.ensemble import RandomForestRegressor
opt_rnd_reg_Nan = RandomForestRegressor(n_estimators= 444,min_samples_split=10, min_samples_leaf=1,
                                     max_features= 'sqrt', max_depth= 10, bootstrap=False )
opt_rnd_reg_Nan.fit(train_X_1, (train_y_1.values.ravel()))

RandomForestRegressor(bootstrap=False, max_depth=10, max_features='sqrt',
                      min_samples_split=10, n_estimators=444)

In [34]:
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(val_y, opt_rnd_reg_Nan.predict(val_X))

In [35]:
mse1

10635.006414852014

In [44]:
import xgboost as xgb
XGB = xgb.XGBRegressor(subsample = 0.6, n_estimators =  1000, 
                       max_depth =  5, learning_rate =  0.01, colsample_bytree =  0.7999999999999999, 
                       colsample_bylevel =  0.6)

XGB.fit(train_X, train_y.values.ravel())

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=0.6, colsample_bynode=None,
             colsample_bytree=0.7999999999999999, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [37]:
mse5 = mean_squared_error(val_y, XGB.predict(val_X))
mse5

9632.251767025477

In [38]:
pred_1 = opt_rnd_reg_Nan.predict(val_X)
pred_2 = XGB.predict(val_X)

In [39]:
pred_final = (pred_1+pred_2)/2.0

In [40]:
mean_squared_error(val_y, pred_final)

9978.318278198292

In [45]:
pred_xgb = XGB.predict(test_X)

In [46]:
output_df = pd.DataFrame()
output_df['Id'] = test_ids
output_df['Predicted'] = pred_xgb
output_df.to_csv('xgb_5_baseline.csv', index = False)

In [43]:
test_y = nopt_rnd_reg_Nan.predict(test_X)
output_df = pd.DataFrame()
output_df['Id'] = test_ids
output_df['Predicted'] = test_y
output_df.to_csv('nan_11_baseline.csv', index = False)

NameError: name 'nopt_rnd_reg_Nan' is not defined

In [ ]:
pred_1_f = opt_rnd_reg_Nan.predict(test_X_old)
pred_2_f = XGB.predict(test_X_old)
pred_3_f = mlp.predict(test_X_old)
pred_final_f = (pred_1_f+pred_2_f+pred_3_f)/3.0
pred_final_f

In [ ]:
mse2 = mean_squared_error(val_y, mlp.predict(val_X))
mse2

In [ ]:
y_pred = mlp.predict(val_X)

In [ ]:
train_X = train_X.mask(train_X.sub(train_X.mean()).div(train_X.std()).abs().gt(3))
train_X

In [ ]:
y_pred

In [ ]:
val_y

In [ ]:
from sklearn.ensemble import HistGradientBoostingRegressor
HGB = HistGradientBoostingRegressor()
HGB.fit(train_X, train_y)